name: Auto Comment Bot

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on Issue or PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = context.payload.issue || context.payload.pull_request;
            const number = issue.number;
            const repo = context.repo;
            await github.rest.issues.createComment({
              owner: repo.owner,
              repo: repo.repo,
              issue_number: number,
              body: "🚀 Thanks for your contribution! A team member will review this soon. 😊"
            });
